Faq:
  entities:
    faq_category:
      fields:
        - name: name
          type: string
          required: true
            - name: image
              type: string
              required: false